### PR TITLE
Ability to enter a witness username manually

### PR DESCRIPTION
**Pull request by Someguy123**
image

### CODE REVIEW

**Comment by valzav** [comment]
Could you put the input box at the bottom instead of top?

**Comment by Someguy123** [comment]
Done.
image

**Comment by valzav** [comment]
Great! I will merge it but please submit it next time to develop branch - master is only for the stable version.

**Comment by Someguy123** [comment]
Ah okay, thanks valzaz. I'll keep that in mind.

I saw other PR's to the master branch, plus there's nothing in the README to say this, or any contributing guidelines etc...

**Pull request merged**
