### PR TITLE
Split Blog tab into Blog and Resteemed tabs

### PR DESCRIPTION
**Pull request by thebitcoiner**
For issue #616

Needs API change from PR https://github.com/steemit/steem/pull/678

Post: https://steemit.com/steemit/@bitcoiner/resteemed-tab-has-been-developed-with-steemd-backend-change

### CODE REVIEW

**Comment by roadscape** [comment]
Thanks, it works quite well! Let's get this implemented in the backend then perform some final testing.

**Comment by thebitcoiner** [comment]
Glad to hear!

**Comment by sneak** [comment]
I'm not sure that we want to do this.  This removes a lot of the power of resteeming.

**Comment by jcalfee** [comment]
@sneak, when I follow someone I will still see their blogs and resteems merged together.  This change only affects the tabs when you navigate to steemit.com/@user ..   Does this address your concern?

**Comment by sneak** [comment]
Yes - if someone resteems something, it is reasonable they want it to appear in their chronological list at steemit.com/@username.

**Comment by TimCliff** [comment]
Hi @sneak - when Dan made the announcement about the new resteem feature a few months back, he listed splitting resteem posts from regular blogs as one of the future enhancements that would be made.

There probably are some users who like it the way it is, but most people that I talk to really don't like that both 'self created' content and resteems show up in the same tab.

**Comment by TimCliff** [comment]
Here is a link to the post:
https://steemit.com/steemit/@dantheman/introducing-the-reblog-button

It lists "_Ability to separate your content from 'reblogged content'_".

The design was left open for interpretation though. 

Another option that was proposed was to keep them together in the same tab, but give users the option to filter out the resteemed content.

**Comment by pfunks** [comment]
@sneak I have personally avoided resteeming entirely because I do not want other people's posts showing in the only place on Steemit that lists my own posts, going back to the beginning. I would **love** to be able to resteem but I do not want to make a mess of my own post listing page. There was massive support on @thebitcoiner's post for this change, including mine.

**Comment by sneak** [comment]
This is a distraction from our growth-focused tasks.

There is no massive support for anything on steemit.com right now because there is no massive audience on steemit.com right now.  If 100% of the people using the platform every day supported something, even that is not massive.

Making the platform massive requires a lot of large projects coming together at once, and not rearranging deck chairs.

**Comment by pfunks** [comment]
How is it a distraction? It's built. Massive support in Steem means stake-weighted votes and quite a lot of stake voted on the post, a lot of individuals voted on the post, and it has many positive comments. The most critical comment in the post put forward an alternative but similar idea of separation.

**Comment by valzav** [comment]
Rather than splitting Blog into two tabs we decided to add some more filters to Blog page so users would be able to filter posts by author (including blog's owner) and by tag.

**Comment by TimCliff** [comment]
Sounds good! There were a few people that wanted them to remain combined, and lots that wanted them split. It sounds like this will make everyone happy.

Is there still a need for https://github.com/steemit/steem/pull/678 anymore?

**Comment by valzav** [comment]
@TimCliff I'm not sure if we need https://github.com/steemit/steem/pull/678 anymore

**Comment by pfunks** [comment]
https://steemit.com/steemit/@tarazkp/steemit-development-profile-resteem-filter

**Pull request closed without merging**
