### PR TITLE
use local intl polyfill

### PR DESCRIPTION
**Pull request by valzav**

### CODE REVIEW

**Comment by Undeadlol1** [comment]
Nice. I have been struggling with this a lot.
Thanks.

**Comment by valzav** [comment]
@Undeadlol1 it requires some more testing in different browsers without native Intl support, I've tested it only in FF 28

**Comment by Undeadlol1** [comment]
I tested it in latest Opera, FireFox, Safari and Chrome browsers. Everything seems to work fine

**Comment by sneak** [comment]
Fixes #770

**Comment by valzav** [comment]
could somebody review and merge this?

**Comment by mcifani** [comment]
@valzav np will review

**Comment by mcifani** [comment]
Tested with: Chrome(55.0.2883.95), Firefox(50.1.0), Safari(9.1.2) all w/ native support. Tested on BrowserStack with Safari(8), Firefox(35) without native support. No issues found.

**Pull request merged**
