### PR TITLE
Fix prop warnings, 'npm cache clean' required before 'npm i'

### PR DESCRIPTION
**Pull request by svk31**
I've made some minor updates to @valzav's react-foundation-components repo that fixes the prop warnings we've been getting. At least in my testing I needed to clean the npm cache in order to get the latest version of the repo when installing.

### CODE REVIEW

**Comment by roadscape** [comment]
I'm getting the following error:

```
ERROR in ./~/react-foundation-components/lib/util/overlay-trigger/index.js
Module not found: Error: Cannot resolve module 'react-overlays/lib/utils/overlayPositionUtils' in steemit.com/node_modules/react-foundation-components/lib/util/overlay-trigger
 @ ./~/react-foundation-components/lib/util/overlay-trigger/index.js 57:28-84
```

**Comment by roadscape** [comment]
I tried nuking node_modules completely, but still getting the err

**Comment by svk31** [comment]
Did you do `npm cache clean`?

That error indicates you're not getting the latest version, as you can see in the below commit I modified that import: https://github.com/valzav/react-foundation-components/commit/d9a2575840057703fc086acbb2c62cab407f0f0f

**Comment by roadscape** [comment]
```
$ git checkout prop-warning-fixes
$ rm -rf node_modules
$ npm cache clean
$ npm i
...
├── react-foundation-components@0.11.1  (git+https://github.com/valzav/react-foundation-components.git#3f7572ed791094104f79f04cf1ff359f53c54311)
...
```

I'm not sure why npm insists on using this commit. It's from April 11 on the `lib` branch:
https://github.com/valzav/react-foundation-components/commits/lib

**Comment by svk31** [comment]
Same error as roadscape, really strange that you're unable to get the latest version.

**Comment by svk31** [comment]
I've updated the forked repo and pushed a new build to the lib branch instead of master.

**Comment by svk31** [comment]
Recommended steps to update:

```
npm remove react-foundation-components
npm cache clean
npm i react-foundation-components --verbose
```
Verify that the installation used commit `0bccbd96f5313b5b7517cc9de97925016ed67d45`

**Comment by sneak** [comment]
Have y'all tried using yarn?  It sucks **so much** less than npm.

**Comment by svk31** [comment]
It's ready as is, just needs @valzav to check again if it works for him after my changes.

**Comment by valzav** [comment]
@sneak it would be interesting to try **yarn**, I think we can try it along with webpack 2.0. Maybe @svk31 would be interested in this project?

**Comment by valzav** [comment]
Works now after I removed shrinkwrap file. It's very nice to see the warnings have gone!

**Comment by roadscape** [comment]
I've pushed an updated shrinkwrap. Now it makes sense why it was refusing to use anything other than that commit...

**Pull request merged**
