### PR TITLE
Reblogging functionality #203

### PR DESCRIPTION
**Pull request by roadscape**
Working well, waiting for backend.

This should not be merged until https://github.com/steemit/steem/issues/401 is resolved and merged into develop.

### CODE REVIEW

**Comment by jcalfee** [comment]
Can user's reblog twice?  Either way, we should probably know if a post was recently re-blogged.

**Comment by roadscape** [comment]
Users "can" reblog twice, and I'm not sure how the backend disposes of duplicate reblogs. I don't believe it's intended to be able to reblog multiple times.

Afaik, there's no way to know (at least from any steemd API) if a post was recently re-blogged.

In the near future we may have a get_state2 call which will take the current user context into account and return more useful info. Until then, if it's important to save the reblog state we may have to do it in local storage?

**Comment by jcalfee** [comment]
`localStorage.getItem("reblogged") could be localStorage.getItem("reblogged_" + username)`

**Comment by roadscape** [comment]
I added namespacing.. it would be a lot smoother if we had currently logged in user in localStorage and didn't have to wait for the login event. Is there anything preventing us from doing this?

**Comment by roadscape** [comment]
Once this PR gets merged we can test & deploy: https://github.com/steemit/steem/pull/428

**Comment by jcalfee** [comment]
>I added namespacing.. it would be a lot smoother if we had currently logged in user in localStorage and didn't have to wait for the login event. Is there anything preventing us from doing this?

I believe it is in `state.offchain.get('user')` .. Notice, when you go to steemit.com it forwards to your feed before you are logged in.  In incognito you instead see a banner and the mainpage.  Look at App.jsx 204.  @valzav is this the way to do it?

**Comment by jcalfee** [comment]
state.offchain comes out of the mysql database.. So it seems the session is left open and this is loaded on first render.

**Comment by valzav** [comment]
you can use state.offchain.account - this is user's account name stored in cookie

**Comment by roadscape** [comment]
As of this merge, **steemd must be built on or after https://github.com/steemit/steem/commit/354cd6bd353b3b6359d28f878cbb3e375173b661**.

**Pull request merged**
