### PR TITLE
379 config env vars

### PR DESCRIPTION
**Pull request by jcalfee**

### CODE REVIEW

**Comment by jcalfee** [comment]
Remove this line in the deployment, it is not used after this merge requeset:
> cp config/steem-example.json config/steem-dev.json

**Comment by mcifani** [comment]
@jcalfee Are you good with removing this PR?  Not sure if it's still WIP.

**Comment by sneak** [comment]
@mcifani we need this.  @jcalfee could you please fix the conflict and merge this in?  mention me in slack for reapproval if required.

**Comment by sneak** [comment]
Don't merge this yet, there is still work to be done.

**Comment by sneak** [comment]
merged this branch into my WIP one for docker... closing this one.

**Pull request closed without merging**
