### PR TITLE
Update payout options #262

### PR DESCRIPTION
**Pull request by roadscape**

### CODE REVIEW

**Comment by jcalfee** [comment]
Are you really sure about putting defaultPayoutType in local storage?  I think it should be a decision on every post.  This affects the author's income.

**Comment by jcalfee** [comment]
At the very least, make sure `decline payout` is not stored in local storage.  If a user wants to set to 100% SP as a payout that would not be so bad to save.  You could verify by giving them a "remember" link in the form.  If the setting gets changed on a later post after "remember" it could auto-forget and offer to remember again.  But I would not want to save `decline payout`..

**Comment by roadscape** [comment]
How this PR addresses your concerns:

1. The default option is 50%/50%
2. It's a decision on every post
3. When 'Decline Payout' is selected, the color of the text turns Orange to draw attention to it. I don't expect this option will be used often, but when it is selected, it should be clear to the user.

**Comment by jcalfee** [comment]
It looks good.. I think that if you get "decline payout" that is should not save in localstorage.  So the next post will default to 50/50 or 100 depending on the post before it..   or just remove local storage from this drop down.

**Comment by jcalfee** [comment]
If val thinks it is ok he can approve it as is (I don't mind) .. ;)

**Comment by jcalfee** [comment]
The big reason is: this option can't be reversed.  If you accidentally put your hard work in under decline and someone votes you can't remove the post, or change that option.  Do you have users that want to consistently decline payouts?

**Comment by roadscape** [comment]
I suspect users who use the 100% option would prefer the option to be sticky. The concern was avoiding unexpected/inconsistent behavior -- e.g. sometimes the option saves between forms, sometimes it doesn't. I understand that this could be not ideal to users who want to decline payout once, but I expect such cases to be rare overall, and this is why a colored label was added.

The main use case is platform and witness updates -- posts which don't warrant a payout yet deserve to be voted on & still ranked for visibility.

**Comment by roadscape** [comment]
Due to a bug in the backend, posts which do not receive a payout still count against a user's optimal max of 4 posts per day. So it's (currently) not all that useful for users who want to share frequently without any reward while still being eligible for the occasional full reward post.

**Comment by roadscape** [comment]
Also, there is one missing piece of functionality -- a signal that a post has reached its maximum payout. I will update Voting.jsx to check for this case so the UI reflects it.

**Comment by roadscape** [comment]
This PR will conflict with #422. #422 is higher priority.

**Comment by roadscape** [comment]
Since 'Decline Payout' will not be used too often, and it still counts against the optimal 4 posts per day, I concur that simply not saving it is the best way to go for now. I've made that change in my last commit.

I also fixed a bug where comments use the last setting (even though they don't get a select box).

More issues to consider for the future:
 - Payout type should be saved as part of the draft status -- returning to a draft will clear "Decline payment" currently.
 - The split between 100% and 50-50 maybe should probably be *account-level*, and apply to comments as well. "Decline payment" could be a per-post setting.
 - For now it's forcing all comments to 50-50. Might be better to just go 100% SP for all comments.

**Comment by jcalfee** [comment]
Just had an idea..  I think removing decline payout from local storage is still fine.  An alternative was to use the __confirm feature in the transaction if the user were about to decline payout.

**Comment by roadscape** [comment]
> Just had an idea.. I think removing decline payout from local storage is still fine. An alternative was to use the __confirm feature in the transaction if the user were about to decline payout.

I like this idea.. for the first iteration I think either approach is good. A confirm dialog could contain a brief explanation of this feature, but I've also stubbed out a posting help dialog in branch `153-posting-guide` and I envision it explaining all the payment options.

I have rebased this branch with develop now that the ReplyEditor refactor has been merged in, so it's good to go unless you'd like to add __confirm logic!

**Pull request merged**
