### PR TITLE
Add welcome page and link in hamburger and empty blog

### PR DESCRIPTION
**Pull request by thebitcoiner**
For issue #404

Added welcome page that new users redirect to.

A link has been added in the hamburger and in an empty blog.

Related post: https://steemit.com/help/@timcliff/the-official-welcome-to-steemit-landing-page-has-been-submitted-to-github-as-a-pull-request

### CODE REVIEW

**Comment by mcifani** [comment]
Looks good.  One suggestion is we try to get away from .html routes/pages.  Seems a bit cleaner with just "welcome".

**Comment by valzav** [comment]
ok, I will merge it in after today's release

**Comment by thebitcoiner** [comment]
@roadscape The conditional disable of the sanitize filter is done only for the HelpContent, which is the FAQ and welcome pages. As these are from markdown files in the repo and not from a user, it should be safe. The redirect to the welcome page happens on the login page only, which the user gets to after a sign up. If a user logs in through the login modal, there will be no redirect.

@mcifani Agreed. I was following the current naming scheme for other pages on the site. Refactoring these in the future would be a good idea.

@valzav Thank you.

**Comment by roadscape** [comment]
Requested changes:
 - Remove references to SvgImage
 - Rename 'welcome.html' to 'welcome' (we are moving away from this legacy convention)

**Comment by thebitcoiner** [comment]
The requested changes have been implemented.

**Comment by thebitcoiner** [comment]
I believe this is ready to merge and not WIP.

**Comment by roadscape** [comment]
@thebitcoiner - tested and works well! My concern about the new welcome page is that it's a bit monochromatic/dry compared to the current new user landing (but certainly more helpful). I hope you might find time to spruce it up a bit with images and maybe some "quick links" at the top to jump straight into good content. Thanks!

---

image

---

image

**Comment by thebitcoiner** [comment]
Thank you @roadscape! That is a good point. After a new user signs up, they will be brought to this new page instead of their blog.

**Pull request merged**
