### PR TITLE
#1162 Add new sign up link in authenticate popup, change verbiage for…

### PR DESCRIPTION
**Pull request by mcifani**
… authenticate popup to be more descriptive on actual action

### CODE REVIEW

**Comment by sneak** [comment]
i haven't previewed this yet but please make the modal twice as tall and make the signup part the entire bottom half and make the actual "sign up" button huge and colorful (bright green for go or bright steemit blue) with an exclamation point.

button text: "Sign up now and receive FREE MONEY!"

**Comment by sneak** [comment]
basically a 9:16 rectangle about, with the top half for existing users and a giant call to action to signup in the bottom half. a light rule between them to visually differentiate them.

**Comment by sneak** [comment]
and add a GA action on the authenticate/signup modal opening, a GA action on login button, and a GA action on the giant ugly eyesore signup button.

**Comment by sneak** [comment]
The button should be vertically and horizontally centered in the bottom half of the modal and should only have 25-33% margins around it (based on the size of the bottom half of the modal).

**Comment by mcifani** [comment]
Closing for new updates, will re-open later.

**Pull request closed without merging**
