### PR TITLE
translation of markets

### PR DESCRIPTION
**Pull request by roadscape**

### CODE REVIEW

**Comment by sneak** [comment]
@roadscape please test it and finish the WIP before end of week 50 (18 dec).  I want to keep our PR queue small.

**Comment by roadscape** [comment]
rebased

**Comment by roadscape** [comment]
- [ ] app/components/elements/DepthChart.jsx
- [ ] app/components/elements/OrderHistory.jsx
- [ ] app/components/elements/Orderbook.jsx
- [ ] app/components/elements/OrderbookRow.jsx
- [ ] app/components/elements/OrderhistoryRow.jsx
- [ ] app/components/modules/BlocktradesDeposit.jsx
- [ ] app/components/pages/Market.jsx
- [ ] app/utils/MarketClasses.js

**Comment by roadscape** [comment]
@valzav What's the difference between `CURRENCY_SIGN` and `localCurrencySymbol`? 

Currently they are both `$`. 

It sounds like `localCurrencySymbol` depends on user config and `CURRENCY_SIGN` is tied to `DEBT_TOKEN`. If that's the case then we should make sure only `CURRENCY_SIGN` is ever used on market page.

**Comment by valzav** [comment]
@roadscape I'm not aware what's the difference

**Comment by roadscape** [comment]
This is no longer a WIP. Upon review, please **squash and merge**.

**Comment by roadscape** [comment]
@svk31 updated.. if that's all please squash & merge

**Pull request merged**
