### PR TITLE
Adjust author heading

### PR DESCRIPTION
**Pull request by roadscape**
before:

image

after:

image

### CODE REVIEW

**Comment by valzav** [comment]
It wouldn't be nice if you could vertically align left and right parts and match the font size

**Comment by valzav** [comment]
This was incomplete - not adjusted for mobile. Also I think now there is less balance between image and text than it used to be.

**Comment by sneak** [comment]
Then revert it back to before anyone touched it, please.

**Comment by sneak** [comment]
FWIW our article-view overlay modals are pretty terribly broken on mobile as well.  I would like to see us remove the two different views for the article view and just have one.  (Users know how to use the back button, or to middle-click.)

**Pull request merged**
