### PR TITLE
Fixed show more low value posts text (low was hidden)

### PR DESCRIPTION
**Pull request by jcalfee**

### CODE REVIEW

**Comment by roadscape** [comment]
@jcalfee, what happened here, did we make the same change? The only difference I see here is how the space is inserted.

**Comment by jcalfee** [comment]
It was hiding the word "low" ..  This fix is fine, but this needs some more researching.  There are other cases where spaces are being concatenated directly with the return value of `translate`.  I'm not sure why that messed though.  The DOM was actually missing the word "low"...

**Comment by jcalfee** [comment]
I thought this was deployed already. Steemit.com is not showing this issue anymore.

**Comment by roadscape** [comment]
@jcalfee the issue was w/ the locale file, here's the commit which adjusted it: https://github.com/steemit/steemit.com/commit/fbb5084725a0da151e7267adb290ef6be7f8d043

**Comment by jcalfee** [comment]
@roadscape thanks..  Closing: do not merge...

**Pull request closed without merging**
