### PR TITLE
Show Resteemed on Blog

### PR DESCRIPTION
**Pull request by thebitcoiner**
This will allow users to go to a blog and be able to easily tell which posts are from the author and which were resteemed.

The pattern from the feed was followed.

Here is an example of what it is currently:

image

Here is what it will look like:

image

### CODE REVIEW

**Comment by roadscape** [comment]
This may be better solved by having the backend return `first_reblogged_by` for user blog feeds, as this would not require any workarounds on the front end

**Comment by roadscape** [comment]
But if we want to go this route for now, I'd recommend changing

```
 +        if(account && account != content.get('author')) {
 +          reblogged_by = <div className="PostSummary__reblogged_by">
 +                             <Icon name="reblog" /> Resteemed
 +                         </div>
 +        }
 +
```

to

```
          let reblogged_by = content.get('first_reblogged_by')
 +        if(!reblogged_by && account && account != content.get('author')) {
 +            reblogged_by = account // workaround #426
 +        }
          if(reblogged_by) {
```

to leverage the existing html generation logic

**Comment by thebitcoiner** [comment]
Yes, having a way to get first_reblogged_by from backend would be better and will allow for the next step, showing the Resteemed on another tab.

I agree the workaround makes for cleaner code, but getting feedback from others on chat, most have said they don't want to see the " by author" text, just Resteemed, on the blog.

**Comment by thebitcoiner** [comment]
Further feedback? Can we leave as is?

**Pull request merged**
