### PR TITLE
prepend nested comments with dots

### PR DESCRIPTION
**Pull request by valzav**

### CODE REVIEW

**Comment by valzav** [comment]
image

**Comment by sneak** [comment]
:(

**Comment by valzav** [comment]
@sneak it helps to distinguish root comments from replies, the dots are very subtle so they will not add much clutter. I will revert this if there will be some negative feedback.

**Comment by sneak** [comment]
I understand the purpose and the problem it attempts to solve is a real one; i just don't think this is the right solution. 

The correct long term answer is to redesign the comment tree and layout, but in the short term, there are better ways than putting all the visual clutter in there.

**Pull request merged**
